name: Limit pipeline on PR approval

on:
  workflow_dispatch:

jobs:
  lets_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for Open PR to Main
        id: pr-check
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            
            const response = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: context.actor + ':' + context.ref.replace('refs/heads/', '')
            });
            
            const pr = response.data.find(pr => pr.base.ref === 'main');
            if (!pr || pr.state !== 'open') {
              core.setFailed("No open PR found for this branch to 'main'. Exiting.");
              return;
            }
            
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            const approvals = reviews.data.filter(review => review.state === 'APPROVED');
            
            return { pr_exists: true, pr_approved: approvals.length > 0 };
          result-encoding: string

      - name: Test
        run: |
          echo "Running pipeline...."
