name: Limit pipeline on PR approval

on:
  workflow_dispatch:

jobs:
  lets_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Check PR approval status
        id: approval_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --head "$GITHUB_REF_NAME" --json number | jq '.[0].number')
          if [ -z "$pr_number" ]; then
            echo "No open PR found for this branch. Exiting."
            exit 1
          fi
          
          approval_count=$(gh pr reviews "$pr_number" | grep -c "APPROVED")
          if [ "$approval_count" -eq 0 ]; then
            echo "PR is not approved. Skipping the pipeline."
            exit 1
          fi

      - name: Test
        run: |
          echo "Running pipeline...."
