name: Limit pipeline on PR approval

on:
  workflow_dispatch:

jobs:
  lets_go:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - if: github.event.review.state == 'approved'
          run: |
            echo "Running pipeline..."