env:
  TEST: "TEST"

defaults:
    run:
        shell: bash

on:
    workflow_dispatch:
      inputs:
        rc-env:
          description: 'Select env from list:'
          required: true
          type: choice
          options:
            - 'RC1'
            - 'RC2'
            - 'RC3'
            - 'RC4'

jobs:
  job1:
    runs-on: ubuntu-latest
    # Expose step outputs as job outputs
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - name: Install JQ Tool
      uses: mbround18/install-jq@v1

    - id: step1
      run: |
        echo '{
        "messages": "will do the backup on workplace - EU,AU - 6225c3d21fbe4d07b2f55fc4\nuploading gs://dev-datalake-eu/20240226-133024-workplace.tar.gz\nbackup complete\n20240226-133024-workplace.tar.gz\n",
        "backup_file": "20240226-133024-workplace.tar.gz"
        }' > test.json
        test3=$(jq -r '.backup_file' test.json)
        echo "test=$test3" >> "$GITHUB_OUTPUT"
    - id: step2
      run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      backup_file: ${{needs.job1.outputs.output1}}
    steps:
    - run: echo $backup_file ${{needs.job1.outputs.output2}}
