defaults:
    run:
        shell: bash

on:
    push:
        branches:
          - main
    workflow_dispatch:
      inputs:
        Action:
          description: 'rs-create-watcher (Select "true" to build)'
          required: true
          default: 'Destroy'
          type: choice
          options:
            - 'Deploy'
            - 'Destroy'

jobs:
  get-inputs:
        runs-on: ubuntu-latest
        env:
          ACTION: ${{ github.event.inputs.Action }}
        steps:
          - name: Show Test
            run: |
              mkdir test
              cd test
              pwd
          - name: Show Action
            run: |
              echo "This is the action: $ACTION"
          - name: Show Deploy
            if: env.ACTION == 'Deploy'
            run: |
              echo "Action is DEPLOY!"
          - name: Show Destroy
            if: env.ACTION == 'Destroy'
            run: |
              echo "Action is DESTROY!"
            
        
