env:
  TEST: "TEST"

defaults:
    run:
        shell: bash

on:
    workflow_dispatch:
      inputs:
        rc-env:
          description: 'Select env from list:'
          required: true
          type: choice
          options:
            - 'RC1'
            - 'RC2'
            - 'RC3'
            - 'RC4'

jobs:
  job1:
    runs-on: ubuntu-latest
    # Expose step outputs as job outputs
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> "$GITHUB_OUTPUT"
    - id: step2
      run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
